install:
	install:
	@set -e
	@echo "Installing pip packages..."
	pip install --upgrade pip &&\
		pip install -r requirements.txt || (echo "Error: Failed to install packages"; exit 1)
test:
	python -m pytest -vv --cov=main test_*.py

format:	
	black *.py 

lint:
	pylint --disable=R,C --ignore-patterns=test_.*?py *.py
		
all: install lint format test 
